// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrAGdSkFMNDELBiOoEKW-4-hnZb6K9Go',
    appId: '1:785939521100:web:21aab41cfe94497b67dee9',
    messagingSenderId: '785939521100',
    projectId: 'slipbuddy-fba3e',
    authDomain: 'slipbuddy-fba3e.firebaseapp.com',
    storageBucket: 'slipbuddy-fba3e.appspot.com',
    measurementId: 'G-E8W9ML16HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX-su1LxLzi3VpBKLJEB2FDyMzwv_6dBE',
    appId: '1:785939521100:android:0d8c1c9b0f31875767dee9',
    messagingSenderId: '785939521100',
    projectId: 'slipbuddy-fba3e',
    storageBucket: 'slipbuddy-fba3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UIpkCbFJQx9hylwV_QHj4KY-uS36Rl8',
    appId: '1:785939521100:ios:f8522e02de67582067dee9',
    messagingSenderId: '785939521100',
    projectId: 'slipbuddy-fba3e',
    storageBucket: 'slipbuddy-fba3e.appspot.com',
    iosBundleId: 'com.gs.slipbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UIpkCbFJQx9hylwV_QHj4KY-uS36Rl8',
    appId: '1:785939521100:ios:f8522e02de67582067dee9',
    messagingSenderId: '785939521100',
    projectId: 'slipbuddy-fba3e',
    storageBucket: 'slipbuddy-fba3e.appspot.com',
    iosBundleId: 'com.gs.slipbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYrAGdSkFMNDELBiOoEKW-4-hnZb6K9Go',
    appId: '1:785939521100:web:66bd7cc3e5939edf67dee9',
    messagingSenderId: '785939521100',
    projectId: 'slipbuddy-fba3e',
    authDomain: 'slipbuddy-fba3e.firebaseapp.com',
    storageBucket: 'slipbuddy-fba3e.appspot.com',
    measurementId: 'G-LT19D0REYE',
  );
}
